### PR TITLE
Value widget: support for 0 & unset twin values

### LINKED ISSUE #416: Value widgets showing placeholder when value is 0
**Describe the bug**
When the value for a value widget is 0, the value widget shows a placeholder rather than the actual value.

**To Reproduce**
1. Create a value widget based on a numeric property
2. Set numeric property on twin to 0
3. Change to viewer and view value widget in behavior modal
4. See placeholder

**Expected behavior**
Value widget shows value on twin if present and no value if not present

**Screenshots**
image

**Browser (please complete the following information):**
 - Chrome

### PR DESCRIPTION
**Pull request by ccrowley96**
### Summary of changes 🔍 
- fixes #416 
- Support for values which parse to 0, previously treated as falsy rendering a value placeholder
- Support for unset twin values, now rendering as `'--'` rather than a value placeholder

## Unset property
image

## 0 value
image

### Testing 🧪
- Create a numeric value widget
- Set the value to 0 (update the twin property driving the expression such that the expression results in 0) & verify the value widget shows 0
- Unset the property on the twin that is linked to the value widget & verify the widget shows '--' rather than '123' or whatever the value placeholder for that type is

### Checklist ✔️
- [x] Linked associated issue (if present)
- [x] Added relevant labels
- [x] Requested developer reviews
- [ ] Request UI review from design / PM
- [ ] Verify all code checks are passing

### CODE REVIEW

File: src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx [hunk 1]
```diff
@@ -34,26 +37,35 @@ export const ValueWidget: React.FC<IProp> = ({ widget, placeholderValues }) => {
...
 
     const styles = getStyles(theme);
     return (
         <div className={styles.container}>
             <div className={styles.expressionValueContainer}>
                 <FormattedValue
                     locale={i18n.language as Locale}
-                    value={
-                        parsedValue ||
-                        (placeholderValues?.[type] ??
```
Comment (msnyder-msft) [inline src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx:54]: this seems like now we won't pass the placeholder value ever?

File: src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx [hunk 2]
```diff
@@ -34,26 +37,35 @@ export const ValueWidget: React.FC<IProp> = ({ widget, placeholderValues }) => {
...
-                            getValuePlaceholders(t)[type])
-                    }
+                    value={parseResult.value}
+                    isValid={parseResult.isValid}
```
Comment (msnyder-msft) [inline src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx:68]: not sure I totally track on the naming of "isValid" but functionally it seems good.

File: src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.styles.ts [hunk 3]
```diff
@@ -65,6 +66,18 @@ export const getStyles = memoizeFunction((theme: Theme) =>
                 ...overflowStyles
             } as IStyle
         ],
+        expressionValueInvalidPlaceholder: [
```
Comment (msnyder-msft) [inline src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.styles.ts:69]: do we really need different styles for this rendering? It seems like it ought to be exactly the same as the value rendering?

**Review by msnyder-msft — APPROVED** [review]

File: src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx (hunk 1 above)
Comment (ccrowley96) [reply src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx:54]: Moved this logic into the useMemo

File: src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx (hunk 2 above)
Comment (ccrowley96) [reply src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx:68]: Will replace with explicit setting & checking of `null` rather than an additional variable

File: src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.styles.ts (hunk 3 above)
Comment (ccrowley96) [reply src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.styles.ts:69]: '--' was tiny with the FontSize.20 styles.  Created this style to make it more visible
